EPOCHS: 10                # number of epochs to train the model
LEARNING_RATE: 0.0001     # learning rate
TRAIN_BATCH_SIZE: 100     # batch size for training
DATA_TRAIN_FOLDER: "data/train"     #folder with the training examples