epochs: 10                # number of epochs to train the model
learning_rate: 0.0001     # learning rate
batch_size: 100     # batch size for training
data_train_folder: "data/train"     #folder with the training examples
data_test_folder: "data/test"
model_out_path: "models/my_model"